apiVersion: batch/v1
kind: Job
metadata:
  name: dummy
spec:
  template:
    spec:
      containers:
      - name: dummy
        image: docker.io/blumenstiel/claimed-dummy:0.2
        command: ["/opt/app-root/bin/python","/opt/app-root/src/dummy.py"]
        env:
        - name: log_level
          value: value_of_log_level
        - name: seconds
          value: value_of_seconds
        - name: shcode
          value: value_of_shcode
        - name: pycode
          value: value_of_pycode
      restartPolicy: OnFailure
      imagePullSecrets:
        - name: image_pull_secret