apiVersion: batch/v1
kind: Job
metadata:
  name: util-cos
spec:
  template:
    spec:
      containers:
      - name: util-cos
        image: docker.io/romeokienzler/claimed-util-cos:0.39
        workingDir: /opt/app-root/src/
        command: ["/opt/app-root/bin/ipython","claimed_util-cos.ipynb"]
        env:
        - name: log_level
          value: value_of_log_level
        - name: cos_connection
          value: value_of_cos_connection
        - name: local_path
          value: value_of_local_path
        - name: recursive
          value: value_of_recursive
        - name: operation
          value: value_of_operation
      restartPolicy: OnFailure
      imagePullSecrets:
        - name: image_pull_secret