name: Build and push CLAIMED operators

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
env:
  version: 0.1
  repository: docker.io/romeokienzler

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.CR_USER }}
        password: ${{ secrets.CR_PASSWORD }}
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install claimed-c3
    - name: Build operators with C3
      run: bash .github/build_operators.sh
